language: go

go:
  - 1.9.x
  - 1.8.x

before_install:
  - sudo apt-get -qq update

script:
  - make
  - go test -v -tags json1 -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
