language: go

go:
  - "1.10"
  - "1.9"
  - "1.8"

before_install:
  - sudo apt-get -qq update

script:
  - make
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
